### ISSUE TITLE
halt at run

### ISSUE THREAD

**Issue by DeminAO** [jekyll2014/VoiceAssistant#2]
![image](https://user-images.githubusercontent.com/57270583/160418202-5e07e3ad-8bab-40d7-b001-8fba5cf66d06.png)

При старте завершает работу при отсутствии папки model:
![image](https://user-images.githubusercontent.com/57270583/160418558-fbb37f58-8fd8-4172-af46-0ad80a47c8c7.png)

Правильней было бы эту папку здесь же и создавать или не завершать работу программы:
![image](https://user-images.githubusercontent.com/57270583/160418934-966c7d7f-af04-4337-bb24-a2d5228a9897.png)

**Comment by DeminAO** [comment]
а то и файла лога нет же

**Comment by jekyll2014** [comment]
К сожалению, папку создать будет недостаточно - там еще модель должна быть, иначе VOSK упадет, но уже жестче.
Но согласен - надо бы прикрутить вменяемое сообщение об ошибке.
Про логирование я думаю, но пока не до него. Да и не совсем понятно, кто на этот лог смотреть будет - программа-то чисто пользовательская, обывательская. Серьезной поддержки по ней пока не планируется.

**Comment by jekyll2014** [comment]
Проверил код - вроде, и сообщение сейчас вполне понятное, так что закрываю.

**Comment by jekyll2014** [comment]
Closed as no reasonable work around found.
