### ISSUE TITLE
VOSK: memory is corrupt

### ISSUE THREAD

**Issue by DeminAO** [jekyll2014/VoiceAssistant#3]
При создании пустой папки:

![image](https://user-images.githubusercontent.com/57270583/160420116-5b41b569-b423-4671-8418-57af59038d09.png)

это исключение не обрабатывается, на удивление:
![image](https://user-images.githubusercontent.com/57270583/160420832-dde8437c-cae0-49c2-bd79-176a7aa8fe39.png)

тип исключения: System.AccessViolationException

**Comment by jekyll2014** [comment]
Весьма вероятная ситуация, но, к сожалению, обработка этого исключения не имеет смысла, помимо окультуривания вывода в консоль. Ради замены ругани от VOSK на аккуратную надпись "модель распознавания не найдена или испорчена" впопыхах этого делать не стоит. Все рекомендации говорят о том, что прежде чем такое перехватывать, надо хорошо подумать, стоит ли. К сожалению, есть более насущные задачи (правка алгоритма парсинга, рефакторинг распознавания чисел и написание новых плагинов).
