### ISSUE TITLE
[proposed question] Будет ли поддержка подтверждения и цепочки комманд?

### ISSUE THREAD

**Issue by mdimai666** [jekyll2014/VoiceAssistant#4]
Спасибо за проект. Впервые вижу из распознователей чтобы работало так плавно и быстро. 

## Подтверждение
Например 
 - "Хочу заказать воду"
 -  в ответ - "Подтверждаете заказ одной бутыля воды из Everest?"
 - Да
 - Заказ оформлен.

## Цепочки
Например 
- "Закажи пиццу", в ответ 
- "Какой вкус предпочитаете Пепперони, Сырный, Сальвадор"
- Сырный
- Какой картой оплатить?
- VISA
- Заказ успешно отправлен.

**Comment by jekyll2014** [comment]
На уровне ядра обрабатывать диалоги смысла все равно нет - это надо делать на уровне плагина. Так что расширять стандартную структуру команд я не планирую. А диалог можно реализовать хоть прямо сейчас - завести команды а все варианты ответов и в плагине сделать стейт-машину, которая будет эти команды обрабатывать. Но в этом случае постоянно надо будет произносить ключевое слово.
Второй вариант - команда нужна всего одна - для запуска плагина, а дальше плагин сам произносит вопросы, ловит поток распознанных слов и из него выбирает ответы. Ничего доделывать в ядре не надо, но, конечно, надо писать отдельный плагин.
